broker = "192.168.1.14:1883"

[[topics]]
name = "zigbee2mqtt/LiXee ZLinky"
interval = 60
fields = [
    "apparent_power",
    "available_power",
    "current_summ_delivered",
    # "current_tarif", string
    "linkquality",
    # "meter_serial_number", string
    "rms_current",
    "rms_current_max"
]
